define(function(require, exports, module){/*
  THIS FILE WAS AUTOGENERATED BY mode.tmpl.js
*/
"use strict";
var oop = require("../lib/oop");
var JavaScriptBehaviour = require("./behaviour/javascript").JavaScriptBehaviour;
var JavaScriptFoldMode = require("./folding/javascript").FoldMode;
var tsMode = require("./typescript").Mode;
var Mode = function () {
    tsMode.call(this);
    this.$highlightRuleConfig = { jsx: true };
    this.foldingRules = new JavaScriptFoldMode();
    this.$behaviour = new JavaScriptBehaviour();
};
oop.inherits(Mode, tsMode);
(function () {
    this.$id = "ace/mode/tsx";
}).call(Mode.prototype);
exports.Mode = Mode;

});